wasm id_us_a.asm -i=h -mf -5r -w4 -e25 -zq
wpp386 gamepal.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 id_ca.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 id_in.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 id_pm.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 id_sd.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 id_us_1.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 id_vh.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 id_vl.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 signon.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_act1.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_act2.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_agent.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_debug.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_draw.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_game.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_inter.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_main.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_menu.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_play.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_state.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wpp386 wl_text.cpp -i=h -w4 -e25 -j -zp1 -zq -od -d2 -5r -bt=dos -mf
wlink name wolf3d SYS dos4g op inc op m op maxe=25 op q file *.obj
